#!/bin/sh
# Copyright (c) 2023 noOvertimeGroup
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# 定义正则表达式
regex="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?: .+"

# 读取每个推送的引用
while read oldrev newrev refname; do
    # 获取新引用的所有提交
    commits=$(git rev-list $oldrev..$newrev)

    # 检查每个提交的提交信息
    for commit in $commits; do
        # 获取提交信息
        msg=$(git log --format=%B -n 1 $commit)

        # 检查提交信息是否符合规范
        # shellcheck disable=SC2039
        if [[ ! $msg =~ $regex ]]; then
            echo "提交 $commit 不遵循常规提交准则。请参考：(常规提交规范)[https://www.conventionalcommits.org/en/v1.0.0/#summary]"
            exit 1
        fi
    done
done