#!/bin/sh

# Copyright (c) 2023 noOvertimeGroup
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# 函数：运行测试并返回结果
run_tests() {
  local tests="go test ./... -race -cover -failfast"
  printf "Running go test...\n"
  $tests
}

# 函数：运行代码检查并返回结果
run_linter() {
  local linter="golangci-lint run"
  printf "Running go linter...\n"
  $linter
}

remote=$1
url=$2
printf >&2 "Try pushing $url to $remote\n"

# 运行测试并检查结果
run_tests
if [ $? -ne 0 ]; then
  printf >&2 "Tests failed\n"
  printf >&2 "Check code to pass tests\n"
  exit 1
fi

# 运行代码检查并检查结果
run_linter
if [ $? -ne 0 ]; then
  printf >&2 "Linter failed\n"
  printf >&2 "Check code to pass linter\n"
  exit 1
fi

exit 0